[package]
name = "yew-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stylist = "0.12.1"
yew-router = "0.17"
yew = { version = "0.20", features = ["csr"] }